"""Add reviews and restaurant_subscriptions tables; extend restaurants and restaurant_tiers with new fields and indexes

Revision ID: 5040ab8596ba
Revises: 49f6bff3b001
Create Date: 2026-03-11 16:22:47.449721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5040ab8596ba'
down_revision: Union[str, Sequence[str], None] = '49f6bff3b001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_reservations_reservation_time', 'reservations', ['reservation_time'], unique=False)
    op.create_index('idx_reservations_restaurant_id', 'reservations', ['restaurant_id'], unique=False)
    op.add_column('restaurant_tiers', sa.Column('priority_rank', sa.Integer(), nullable=True))
    op.add_column('restaurant_tiers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('restaurants', sa.Column('total_reviews', sa.Integer(), nullable=True))
    op.add_column('restaurants', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index('idx_restaurants_city', 'restaurants', ['city'], unique=False)
    op.create_index('idx_restaurants_cuisine', 'restaurants', ['cuisine'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_restaurants_cuisine', table_name='restaurants')
    op.drop_index('idx_restaurants_city', table_name='restaurants')
    op.drop_column('restaurants', 'created_at')
    op.drop_column('restaurants', 'total_reviews')
    op.drop_column('restaurant_tiers', 'created_at')
    op.drop_column('restaurant_tiers', 'priority_rank')
    op.drop_index('idx_reservations_restaurant_id', table_name='reservations')
    op.drop_index('idx_reservations_reservation_time', table_name='reservations')
    # ### end Alembic commands ###
