"""Add missing restaurant columns

Revision ID: a846976a7e54
Revises: 39da16adfd2c
Create Date: 2026-03-13 22:49:32.509491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a846976a7e54'
down_revision: Union[str, Sequence[str], None] = '39da16adfd2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_user_preferences_user_cuisine'), table_name='user_preferences')
    op.drop_index(op.f('idx_user_preferences_weight'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_table('reviews')
    op.add_column('restaurants', sa.Column('reservation_count', sa.Integer(), nullable=True))
    op.add_column('restaurants', sa.Column('popularity_score', sa.Float(), nullable=True))
    op.add_column('restaurants', sa.Column('embedding', sa.JSON(), nullable=True))
    op.create_index('idx_restaurants_featured', 'restaurants', ['is_featured'], unique=False)
    op.create_index('idx_restaurants_rating', 'restaurants', ['rating'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_restaurants_rating', table_name='restaurants')
    op.drop_index('idx_restaurants_featured', table_name='restaurants')
    op.drop_column('restaurants', 'embedding')
    op.drop_column('restaurants', 'popularity_score')
    op.drop_column('restaurants', 'reservation_count')
    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('reviews_restaurant_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('reviews_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reviews_pkey'))
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('cuisine', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_preferences_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_preferences_pkey'))
    )
    op.create_index(op.f('idx_user_preferences_weight'), 'user_preferences', ['weight'], unique=False)
    op.create_index(op.f('idx_user_preferences_user_cuisine'), 'user_preferences', ['user_id', 'cuisine'], unique=False)
    # ### end Alembic commands ###
