"""Add table_id foreign key to reservations

Revision ID: ec2d4a9b4ee2
Revises: 18a5ae5abefb
Create Date: 2026-03-11 16:41:11.095100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec2d4a9b4ee2'
down_revision: Union[str, Sequence[str], None] = '18a5ae5abefb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('table_id', sa.Integer(), nullable=True))
    op.create_index('idx_reservations_table_time', 'reservations', ['table_id', 'reservation_time'], unique=False)
    op.create_foreign_key(None, 'reservations', 'restaurant_tables', ['table_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_index('idx_reservations_table_time', table_name='reservations')
    op.drop_column('reservations', 'table_id')
    # ### end Alembic commands ###
