"""Add PostGIS location column to restaurants

Revision ID: 18a5ae5abefb
Revises: 5040ab8596ba
Create Date: 2026-03-11 16:37:24.621710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2.types

# revision identifiers, used by Alembic.
revision: str = '18a5ae5abefb'
down_revision: Union[str, Sequence[str], None] = '5040ab8596ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip PostGIS for now - use regular lat/lon columns
    # We'll add PostGIS later when it's available on the system
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
