"""Add user_preferences table for recommendation engine

Revision ID: 39da16adfd2c
Revises: ec2d4a9b4ee2
Create Date: 2026-03-11 17:31:25.553325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39da16adfd2c'
down_revision: Union[str, Sequence[str], None] = 'ec2d4a9b4ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create user_preferences table
    op.create_table('user_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('cuisine', sa.VARCHAR(), nullable=False),
    sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_preferences_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_preferences_pkey'))
    )
    op.create_index('idx_user_preferences_user_cuisine', 'user_preferences', ['user_id', 'cuisine'], unique=False)
    op.create_index('idx_user_preferences_weight', 'user_preferences', ['weight'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_preferences_weight', table_name='user_preferences')
    op.drop_index('idx_user_preferences_user_cuisine', table_name='user_preferences')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
