"""baseline

Revision ID: 49f6bff3b001
Revises: 
Create Date: 2026-03-11 16:15:26.875367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f6bff3b001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('tier_id', sa.Integer(), nullable=True))
    op.add_column('restaurants', sa.Column('subscription_start', sa.DateTime(), nullable=True))
    op.add_column('restaurants', sa.Column('subscription_end', sa.DateTime(), nullable=True))
    op.add_column('restaurants', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('restaurants', sa.Column('commission_rate', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'restaurants', 'restaurant_tiers', ['tier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurants', type_='foreignkey')
    op.drop_column('restaurants', 'commission_rate')
    op.drop_column('restaurants', 'is_featured')
    op.drop_column('restaurants', 'subscription_end')
    op.drop_column('restaurants', 'subscription_start')
    op.drop_column('restaurants', 'tier_id')
    # ### end Alembic commands ###
